#! /bin/sh

pgrep -x sxhkd > /dev/null |
pgrep -x picom > /dev/null
pgrep -x polybar > /dev/null
pgrep -x dunst > /dev/null
pgrep -x nm-applet > /dev/null
pgrep -x lxpolkit > /dev/null

###############################################################################
##                                AUTOSTART APPS                              #
###############################################################################

sxhkd &
wmname BSPWM &
picom --no-fading-openclose &
sh $HOME/.config/polybar/launch.sh &
dunst --config $HOME/.config/dunst/dunstrc &
feh --bg-scale "/home/wgparch/Pictures/ALNW/pink-floyd-dark-side-prism.jpg" &
#feh --bg-scale "/home/wgparch/Pictures/ALNW/BlackandWhiteGirl.jpg" &
conky -c ~/.config/conky/sqi-right.conkyrc &
conky -c ~/.config/conky/sqi-left.conkyrc &
xfce4-power-manager &
nm-applet &
lxpolkit &

###############################################################################
##                            GENERAL CONFIGURATION                           #
###############################################################################

bspc monitor primary -d I II III IV V VI VII VIII IX X XI
bspc config border_width         1
bspc config window_gap           3

bspc config top_padding          0
bspc config bottom_padding       0

bspc config normal_border_color  "#ffffff"
bspc config active_border_color  "#ffffff"
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

###############################################################################
##                            WEIRD JAVA WINDOW FIX                           #
###############################################################################

bspc rule -a android-studio state=floating border=off follow=on
nm-applet &
lxpolkit &


