;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘

[colors]
background-bar = #000000
foreground-bar = #ffffff

background-empty = #000000
foreground-empty = #ffffff

background-occupied = #000000
foreground-occupied = #ffffff

background-active = #000000
foreground-active = #ffffff

background-urgent = #bf616a
foreground-urgent = #81a1c1

color-disabled = #bf616a
color-good = #a3be8c

alpha = #00000000

[bar/main]
monitor-fallback =
monitor-strict = false
override-redirect = false
wm-restack = bspwm
enable-ipc = true
bottom = false
fixed-center = true

width = 100%
height = 30
offset-x = 0
offset-y = 0
background = ${colors.background-bar}
foreground = ${colors.foreground-bar}

line-size = 0
line-color = #5e81ac

padding = 0
module-margin-left = 0
module-margin-right = 0

font-0 = "Courier 10 Pitch:size=10;2"
font-1 = "JetBrainsMono Nerd Font:size=10;2"
font-2 = "Font Awesome 7 Brands:size=10;2"
font-3 = "Font Awesome 7 Free Solid:size=10;2"
font-4 = "Symbols Nerd Font:size=10;2"

modules-left = launcher workspaces 
modules-center = date weather
modules-right = cpu memory pulseaudio temperature dunst battery systemmenu

tray-position = right
tray-padding = 1
tray-detached = false
tray-background = ${colors.background-bar}
tray-offset-x = 0
tray-offset-y = 0
tray-maxsize = 12

[global/wm]
margin-bottom = 0
margin-top = 0
include-file = ~/.config/polybar/modules.ini

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false

[module/weather]
type = custom/script
interval = 1800
format = <label>
label = %output%
exec = /home/wgparch/.config/polybar/bspwm-weather.py

#[module/battery]
3type = custom/script
#exec = acpi -b | grep -E -o "[0-9]+%"
#interval = 10
#format = <label>
#format-foreground = ${colors.foreground-bar}
#format-background = ${colors.background-bar}
#label = "Battery %output%"

[module/battery]
type = custom/script
exec = acpi -b | grep -E -o "[0-9]+%"
interval = 10
format = <label>
format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = #f9e2af
format-foreground = ${colors.foreground-bar}
format-background = ${colors.background-bar}
label = "%output%"
